export const SAVE_USER_INFO = 'SAVE_USER_INFO';
export const CHANGE_STATUS_BAR = 'CHANGE_STATUS_BAR';
export const UPDATE_USER_LASTNAME = 'UPDATE_USER_LASTNAME';
export const UPDATE_USER_FIRSTNAME = 'UPDATE_USER_FIRSTNAME';
export const UPDATE_USERNAME = 'UPDATE_USERNAME';
export const UPDATE_USER_BIRTHDATE = 'UPDATE_USER_BIRTHDATE';
export const UPDATE_GEOLOCATION_MECHANISM = 'UPDATE_GEOLOCATION_MECHANISM';
export const UPDATE_EMAIL_MECHANISM = 'UPDATE_EMAIL_MECHANISM';